version: 2

updates:
  # Check for updates to GitHub actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  # Check for updates to Python packages
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
