# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Henrik Brix Andersen <henrik@brixandersen.dk>
#
# SPDX-License-Identifier: Apache-2.0

version: 2

updates:
  # Check for updates to GitHub actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "github: "
  # Check for updates to Python packages
  - package-ecosystem: pip
    directory: /scripts
    schedule:
      interval: daily
    commit-message:
      prefix: "scripts: "
  # Check for updates to Python packages for the documentation
  - package-ecosystem: pip
    directory: /doc
    schedule:
      interval: daily
    commit-message:
      prefix: "doc: "
