# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Henrik Brix Andersen <henrik@brixandersen.dk>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_USB_DEVICE_STACK_NEXT=y

# Hardened configuration
CONFIG_BOOT_BANNER=n
CONFIG_BUILD_OUTPUT_STRIPPED=y
CONFIG_PRINTK=n
CONFIG_STACK_SENTINEL=y
CONFIG_OVERRIDE_FRAME_POINTER_DEFAULT=y

# Arm-specific hardened configuration
CONFIG_FAULT_DUMP=0
