name: Documentation

on:
  pull_request:
    branches:
      - main
      - v*-branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          pip install -r doc/requirements.txt

      - name: Build
        run: |
          cd doc
          env SPHINXOPTS="-W" make html

      - name: Setup pages
        if: github.event_name != 'pull_request'
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build/html

      - name: Upload artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          path: doc/build/html

  deploy:
    runs-on: ubuntu-24.04
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
