name: Build and release firmware

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created, edited]

jobs:
  build:
    name: Build firmware for targets
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - board: entree
            toolchain: arm-zephyr-eabi
            target_name: entree
            build_flags: --sysbuild
            extra_flags:
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          path: app-workspace

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.12

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@700109a78599c7bb26585f2fb3d2411d65381b9d # v1
        with:
          app-path: app-workspace
          toolchains: ${{ matrix.toolchain }}

      - name: Apply patches
        working-directory: app-workspace
        run: west patch apply

      - name: West config
        working-directory: app-workspace
        run: west config build.cmake-args -- ${{ secrets.CMAKE_BUILD_ARGS }}

      - name: Build firmware
        working-directory: app-workspace
        shell: bash
        run: west build -p always -b ${{ matrix.board }} app ${{ matrix.build_flags }} -- ${{ matrix.extra_flags }}

      - name: Rename artifacts
        working-directory: app-workspace
        run: |
          mkdir -p artifacts
          if [ -f build/app/zephyr/zephyr.signed.bin ]; then
            cp build/app/zephyr/zephyr.signed.bin artifacts/${{ matrix.target_name }}_app.signed.bin
          fi
          if [ -f build/mcuboot/zephyr/zephyr.bin ]; then
            cp build/mcuboot/zephyr/zephyr.bin artifacts/${{ matrix.target_name }}_mcuboot.bin
          fi
          if [ -f build/zephyr/zephyr.bin ]; then
            cp build/zephyr/zephyr.bin artifacts/${{ matrix.target_name }}.bin
          fi

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: firmware-${{ matrix.target_name }}
          path: app-workspace/artifacts/*

  release:
    name: Attach firmware to GitHub Release
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Download all artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Upload Release Assets
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2
        with:
          files: artifacts/firmware-*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
